export const IMAGES = {
  homeLogo: require('../../assets/images/homePageLogo.png'),
  backgroundImg: require('../../assets/images/BackgroundImg.png'),
  eventDummy: require('../../assets/images/eventDummyy.jpeg'),
  appIcon: require('../../assets/images/appIcon.png'),
  dummyRegion: require('../../assets/images/dummyRegion.png'),
  dummyClub: require('../../assets/images/dummyClub.png'),
  event_img_1: require('../../assets/images/event_img_1.png'),
  ground_picture: require('../../assets/images/ground_picture.png'),
  location_icon: require('../../assets/images/location_icon.png'),
  flyer_icon: require('../../assets/images/flyer_icon.png'),
  search: require('../../assets/images/search.png'),
  club_header: require('../../assets/images/club_header.png'),
  club_route: require('../../assets/images/club_route.png'),
  club_master: require('../../assets/images/club_master.png'),
  img: require('../../assets/images/img.png'),
  img_1: require('../../assets/images/img_1.png'),
  img_2: require('../../assets/images/img_2.png'),
  img_3: require('../../assets/images/img_3.png'),
  radius_ic: require('../../assets/images/radius_ic.png'),
  checkmarkcircle: require('../../assets/images/checkmarkcircle.png'),
  exclamation: require('../../assets/images/exclamation.png'),
};
