
  def node_require(script)
   # Resolve script with node to allow for hoisting
   require Pod::Executable.execute_command('node', ['-p',
     "require.resolve(
       '#{script}',
       {paths: [process.argv[1]]},
     )", __dir__]).strip
 end

# Use it to require both react-native's and this package's scripts:
 node_require('react-native/scripts/react_native_pods.rb')
 node_require('react-native-permissions/scripts/setup.rb')

platform :ios, '13.4'
prepare_react_native_project!


# ⬇️ uncomment the permissions you need
setup_permissions([
  'LocationWhenInUse',
  'LocationAlways',
])


# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'ToilettenFinder' do
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  config = use_native_modules!

#   pod 'leveldb-library', :modular_headers => true
#   pod 'Firebase', :modular_headers => true
#   pod 'FirebaseDatabase', :modular_headers => true
#   pod 'FirebaseStorage', :modular_headers => true
#   pod 'FirebaseAuthInterop', :modular_headers => true
#   pod 'FirebaseCoreExtension', :modular_headers => true
#   pod 'GTMSessionFetcher', :modular_headers => true
#   pod 'FirebaseCoreInternal', :modular_headers => true
#   pod 'GoogleUtilities', :modular_headers => true
#   pod 'FirebaseCore', :modular_headers => true
#   pod 'FirebaseAppCheckInterop', :modular_headers => true
#
#   pod 'RNFBStorage', :path => '../node_modules/@react-native-firebase/storage'

  use_react_native!(
    # use_frameworks! :linkage => :static
    # RNFirebaseAsStaticFramework = true
    :path => config[:reactNativePath],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'ToilettenFinderTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end